name: Lint

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: hallee/eslint-action@master'
        with:
          node-version: 12
      - run: npm ci
      - uses: eslint/github-action@v0
